class Color(DefaultColor):
    USERNAME_FG = 8
    USERNAME_BG = 251
    USERNAME_ROOT_BG = 209

    HOSTNAME_FG = 8
    HOSTNAME_BG = 7

    HOME_SPECIAL_DISPLAY = True
    PATH_BG = 254
    PATH_FG = 8
    CWD_FG = 8
    SEPARATOR_FG = 251

    READONLY_BG = 209
    READONLY_FG = 15

    REPO_CLEAN_BG = 150  # pale green
    REPO_CLEAN_FG = 235
    REPO_DIRTY_BG = 203  # pale red
    REPO_DIRTY_FG = 15

    JOBS_FG = 14
    JOBS_BG = 8

    CMD_PASSED_BG = 7
    CMD_PASSED_FG = 8
    CMD_FAILED_BG = 9
    CMD_FAILED_FG = 15

    SVN_CHANGES_BG = REPO_DIRTY_BG
    SVN_CHANGES_FG = REPO_DIRTY_FG

    VIRTUAL_ENV_BG = 37
    VIRTUAL_ENV_FG = 0

    GIT_AHEAD_BG = 61
    GIT_AHEAD_FG = 231
    GIT_BEHIND_BG = 61
    GIT_BEHIND_FG = 231
    GIT_STAGED_BG = 25
    GIT_STAGED_FG = 15
    GIT_NOTSTAGED_BG = 136
    GIT_NOTSTAGED_FG = 15
    GIT_UNTRACKED_BG = 124
    GIT_UNTRACKED_FG = 15
    GIT_CONFLICTED_BG = 9
    GIT_CONFLICTED_FG = 15
